owner: monobankcom
repo: upptime

sites:
  - name: monobank.com
    url: https://monobank.com
    
  - name: monobank App
    url: https://app.monobank.com
    
  - name: monobank India
    url: https://monobank.in

  - name: Quote API
    method: POST
    url: https://api.cow.fi/mainnet/api/v1/quote
    headers: ["Content-Type: application/json"]
    body: |
      {
        "kind": "sell",
        "sellAmountBeforeFee": "10000000000000000000",
        "sellToken": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
        "buyToken": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
        "from": "0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B"
      }
      
status-website:
  cname: status.monobank.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime | monobank
  introTitle: "Check real-time data for **monobank App**"
  introMessage: Check real-time data for [**monobank App**](https://app.monobank.com)
  navbar:
    - title: Home
      href: https://monobank.com
    - title: monobank App
      href: https://app.monobank.com    
  assignees:
    - belovolk
    - rdmsh
    - vladtimm
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
